In [1]:
import numpy.random as rnd

In [40]:
x=rnd.seed(0)
arr=rnd.rand(6)
print(arr)
# st=rnd.get_state()
# print("State : ",st)

iar=rnd.randint(1,9,6)
iar1=rnd.random_integers(1,9,9)
print(iar)
print(iar1)
print(rnd.random_sample(5))
print(rnd.ranf(5))
print(rnd.random(5))

print(rnd.choice(iar,5))
print("-"*50)
print(rnd.permutation(9))


[ 0.5488135   0.71518937  0.60276338  0.54488318  0.4236548   0.64589411]
[5 8 7 1 1 5]
[2 7 8 8 9 2 6 9 5]
[ 0.0202184   0.83261985  0.77815675  0.87001215  0.97861834]
[ 0.79915856  0.46147936  0.78052918  0.11827443  0.63992102]
[ 0.14335329  0.94466892  0.52184832  0.41466194  0.26455561]
[1 7 1 7 5]
--------------------------------------------------
[3 2 1 7 8 6 5 4 0]


/home/maniram/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:8: DeprecationWarning: This function is deprecated. Please call randint(1, 9 + 1) instead
  


#### arr

In [41]:
x=rnd.seed(0)
arr=rnd.rand(6)

In [42]:
arr

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ,
        0.64589411])

In [43]:
arr=rnd.rand(6)
arr

array([ 0.43758721,  0.891773  ,  0.96366276,  0.38344152,  0.79172504,
        0.52889492])

In [44]:
x=rnd.seed(0)
arr=rnd.randn(6)

In [45]:
arr

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788])