In [1]:

import numpy as n


In [36]:
a=n.array([(1,2,3),(3,4,5)])

print(a,a.shape,a.itemsize)
print("**************")
ar=n.arange(24)
print(ar,ar.ndim)
br=ar.reshape(2,3,4)
print(br,br.ndim,br.shape)
print("**************")
ar=n.empty([2,3],dtype=int,order='F')
print(ar)
print("**************")
ar=n.ones([2,3],dtype=int,order='F')
print(ar)
print("**************")
ar=n.zeros([2,3],dtype=int,order='C')
print(ar)
print("***** As Array *********")
a=[2,6,3,8]
ar=n.asarray(a,dtype=int,order='C')
print(ar)
print("****** FromBuffer ********")
s='Maniram'
ar=n.frombuffer(s,dtype='S1')
print(ar)
print("******  From Iter ********")
r=range(7)
it=iter(r)
ar=n.fromiter(it,dtype=int)
print(ar)

(array([[1, 2, 3],
       [3, 4, 5]]), (2, 3), 4)
**************
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23]), 1)
(array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]]), 3, (2, 3, 4))
**************
[[1 3 4]
 [2 3 5]]
**************
[[1 1 1]
 [1 1 1]]
**************
[[0 0 0]
 [0 0 0]]
***** As Array *********
[2 6 3 8]
****** FromBuffer ********
['M' 'a' 'n' 'i' 'r' 'a' 'm']
******  From Iter ********
[0 1 2 3 4 5 6]


In [45]:
"""
b=a.reshape(3,2)
print(b,b.shape)
b.shape=(2,3)
print(b,b.shape)
"""
print('*********   Array range ************')
b=n.arange(2,8,2,dtype=int)
print(b)
print('*********   linespace  ************')
b=n.linspace(2,8,9,dtype=float,endpoint=False)
print(b)


*********   Array range ************
[2 4 6]
*********   linespace  ************
[ 2.          2.66666667  3.33333333  4.          4.66666667  5.33333333
  6.          6.66666667  7.33333333]


In [48]:
c=n.array([2,3,4,5],dtype=complex)
print(c)
print(c.shape)
print('*********   logspace  ************')
b=n.logspace(2,8,9,dtype=float,endpoint=False,base=2)
print(b)


[ 2.+0.j  3.+0.j  4.+0.j  5.+0.j]
(4,)
*********   logspace  ************
[   4.            6.34960421   10.0793684    16.           25.39841683
   40.3174736    64.          101.59366733  161.26989439]
