In [19]:
import numpy as n
a=n.arange(24)
b=slice(2,10,3)
print(a[b])
print("*************************")
print(a[2:10:2])
print("***********Two Dimensional array **************")
b=a.reshape(4,6)
print(b)
print("*********   return rows ****************")
print(b[2:4])
print("*********   return rows ****************")
print(b[2:])
print("*********   return cols ****************")
print(b[...,3:])
print("*********   return rows ****************")
print(b[2:,...])



[2 5 8]
*************************
[2 4 6 8]
***********Two Dimensional array **************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
*********   return rows ****************
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
*********   return rows ****************
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
*********   return cols ****************
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]
*********   return rows ****************
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
